### ISSUE TITLE
Missing file: scripts/do_all.sh

### ISSUE THREAD

**Issue by yuzefang96** [skelemoa/tal-hmo#2]
Hi,
I was wondering when you would release the do_all.sh and test.sh file?

**Comment by jazib-sudo** [comment]
> Hi,
> I was wondering when you would release the do_all.sh and test.sh file?


Within a week, every file will be uploaded.

**Comment by shubhamagarwal92** [comment]
Hey, is there an update on this? 
Also, are you planning to upload ops module as called in the `dataset.py`

```
from ops.io import load_proposal_file
from ops.utils import temporal_iou
```

**Comment by jazib-mahmood-attainu** [comment]
> Hey, is there an update on this?
> Also, are you planning to upload ops module as called in the `dataset.py`
> 
> ```
> from ops.io import load_proposal_file
> from ops.utils import temporal_iou
> ```

A little busy with other submissions, will update everything on 20th August.

**Comment by jazib-sudo** [comment]
> Hey, is there an update on this?
> Also, are you planning to upload ops module as called in the `dataset.py`
> 
> ```
> from ops.io import load_proposal_file
> from ops.utils import temporal_iou
> ```

We are lagging due to other submission deadlines, everything will be uploaded on 20th August.
